# Users schema

# --- !Ups

INSERT INTO USER VALUES (1, 'ranjitis@hotmail.com', 'pass', 'rana ranjit', 'singh', '41350220', 1, current_timestamp, current_timestamp);
INSERT INTO USER VALUES (2, 'singh@iterate.no', 'pass', 'iterate', 'singh', '41350220', 0, current_timestamp, current_timestamp);

INSERT INTO article (name, producer, header, teaser, body, published, image_url, owner_id, borrower_id ) values
  ('Hultafors TC 16 XL hammer', 'Hultafors', 'Hultafors TC 16', 'Suverent god hammer til utlån. Godt grep og god kvalitet.', 'Meget godt grep, noe glattere på vått, men sitter fremdeles.Pluss for at grepet kommer i flere størrelser.Kloas utforming gir suveren tilgjengelighet når du trekker ut spiker. Meget god avvibrering og lite tilbakeslag, lav og solid lyd. God utførelse på hodet gir ingen skarpe kanter og lite merker.Hammeren har meget god balanse og solid utførelse', 1, 'http://www.klikk.no/multimedia/archive/00480/hammer__yvind_lie_480130m.jpg', 1, 2),
  ('HPL10RSK', 'Black & Decker', 'HPL10RSK Liten bajonettsag', 'Denne saga ville ikke testerne levere tilbake. Rett og slett fordi den er svært hendig.', 'Ergonomien er god, muligheten for å vinkle skaftet er grei å ha, men ikke noe vi har brukt særlig mye. Den har gummiering på de rette stedene og knapper og brytere er greit plassert. Bladskifte er greit og verktøyløst.Saga egner seg til sporadisk kapping av mindre dimensjoner og rør av alle typer. Intensiv bruk over tid blir for mye for denne saga.', 1, 'http://www.klikk.no/multimedia/archive/00446/test_BD_4_19_jpg_446137b.jpg', 1, 2),
  ('Bosch drill PSR 14,4 LI-2', 'Bosch', 'Bosch batteridrevet bor-/skrumaskin PSR 14,4 LI-2', 'Meget god batteridrill', 'Lithium-ion-teknologi - lett og effektsterk for alle skruoppgaver -med boretrinn - 2-trinnsgir. Ingen minneeffekt, ingen selvutlading: Alltid klar til bruk takket være lithium-ion-teknologi. De utskiftbare lithium-ion-batteriene har svært lang levetid takket være Bosch Electronic Cell Protection (ECP). Den medfølgende laderen lader opp batteriet, enten for seg eller ammen med maskinen.', 1, 'https://www.mpx.no/img/p/400/623414.jpg', 1, 2),
  ('Hanging Toiletry Bag', 'Sea to Summit', 'Hanging Toiletry Bag', 'Sea to Summit Hanging Toiletry Bag er en praktisk toalettmappe med hengekrok. Flere innvendige meshlommer som gir deg et raskt overblikk.', 'Utstyrt med solid U-formet glidelås og opphengskrok.Finnes i to størrelser: Small: 23x15x8 cm, 3 liter, 80 gram Large: 29x23x10 cm, 6 liter, 112 gram Farger: Aubergine/Slate - Lilla Lime/Black - Grønn Midnight/Slate - Blå', 1, 'http://www.outnorth.no/20.0.0.0/8529/cache/8529_d7d3efb7a4ac624c3174a6776cd9a0d8.jpg', 1, 2),
  ('Leatherman - Wave', 'Leatherman', 'Leatherman - Wave', 'Wave er uten tvil Leathermans mest populære multiverktøy.', 'Wave er Leathermans mest populære multiverktøy, og det sier en hel del. Årsaken er nok at det er det ultimate multiverktøyet. Det er blitt kjent for bladene som kan felles ut fra utsiden med bare én hånd. I 2004 ble Wave nydesignet med blant annet lengre blader og en kraftigere tang. På Wave finner du blant annet: 420HC Clip Point kniv 420HC Sheepsfoot Serrated kniv Needlenose tang Vanlig tang Avbiter Stor skrutrekker Saks Tre-/metallfil Diamond-coated fil Sag Flaskeåpner Bokseåpner 8 in | 19 cm linjal Spesifikasjoner: Lengde stengt: 10 cm Vekt: 241 g', 1, 'http://www.outnorth.no/20.0.0.4/40073/cache/40073_5db2d658e9a7c157e8f23618052fa6f3.jpg', 1, 2),
  ('Håndsag Superior 2600XT', '', 'Håndsag Superior 2600XT', 'Kapp- og kløvsag for tre, sponplater og andre moderne bygningsmaterialer', '', 1, 'https://www.mpx.no/img/p/400/801728.jpg', 1, 2),
  ('Arbeidslampe halogen 120W', '', 'Arbeidslampe halogen 120W', 'Effekt: 120W, m/bevegelsessensor', '', 1, 'https://www.mpx.no/img/p/400/801963.jpg', 1, 2);
